# SPDX-FileCopyrightText: 2019-2022 Joonas Javanainen <joonas.javanainen@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: ci
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  check:
    name: Run checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install stable toolchain
        run: |
          rustup toolchain install stable --profile minimal --component rustfmt --component clippy
          rustup default stable
      - name: Cache dependencies
        uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6
      - name: Run checks
        run: cargo check --all
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run clippy
        run: cargo clippy --all

  test:
    name: Run tests
    needs: [check]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.56.0
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal
          rustup default ${{ matrix.rust }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6
      - name: Compile
        run: |
          cargo build --all
          cargo test --all --no-run
      - name: Test
        run: cargo test --all
